### PR TITLE
Adding factory order models

### LINKED ISSUE #74: Importing plates from Factory
# Factory Imports
- [x] Create Order page
- [x] Link Plates to Orders
- [x] Checkbox for adding samples into Plate

## Create Order page
For any given synthesis company, we want to see information about orders that we currently have out with them. This will require a few different fields:

- status ( String, Enum=['Planned','In-Production','Complete','Abandoned'] )
- start date ( DateTime [user defined] ) 
- finish date ( DateTime [user defined] )
- estimated price ( Float )
- real price ( Float )
- invoices ( List of Invoice objects )

Invoices, the last object, are just PDF files that have the status "Unpaid" and "Paid" along with a section for "notes" about that invoice. Invoices are simply to track expenditures so I can sync up with our financial director.

Both the start date and finish date should allow user defined data (like a calendar pop up), so that is very easy to import older data.

I imagine a simple form interface where you can manually input each one of those data points.

## Link Plates to Orders
When importing a plate, there should be the option to import it as associated with a DNA Order. Later, we can track which plates came from which particular orders.

## Checkbox for adding samples into Plate
When you import a plate into the system, you have the option to add a sample in as well. If a plate is associated with an order, first we would check for if a sample is already used for that particular part. If it is, we simply use that sample. If not, we must generate a sample object.

When you click the checkbox, you also have the option to put in the Vendor, which is the Sample.vendor for all samples generated.

### Sample import
For each row in a plate map, we specifically care about the "Name", which maps to the Part.gene_id
```
row['Name'] == Part.gene_id -> sample.part_uuid
"Confirmed" -> Sample.status
"Vendor_Confirmed" -> Sample.evidence # Replaces "Twist_Confirmed"
Vendor -> Sample.vendor
```
Each sample is put into the well that is also generated by the line of the plate map.

### LINKED ISSUE #75: Reorganize images in docs/usage folder
There are a ton of images I'm taking for the usage docs, and I'd like to put them cleanly into an img subfolder. I've done this locally and will push with the current PR when it's ready.

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add FactoryOrder, Invoice, and Vendor to factory models, along with the checkbox to import samples when a plate map is import, and select an associated FactoryOrder. This will close #74 and close #75. 

The logic for the import is defined in `fg/apps/factory/views/twist.py` and since it's confusing, @Koeng101 I'd like you to fully review it, along with all the new models defined, before any kind of merge and update is done to the server. If you want to test locally, you can also clone the repository and follow the instructions to deploy with Docker.

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Wow that was the fastest review ever - did you look it over carefully I hope?

And you want to update the server then?

**Comment by Koeng101** [comment]
I actually looked at it almost immediately as it came into my inbox and then just browsed through the commits.
```
                # Look up the associated part
                part = Part.objects.get(gene_id=name)

                # Look for a Sample for a Part WITHIN a FactoryOrder
                sample = None
                for plate in factory_order.plates.all():

                   # Look for a sample already associated with plate from the factory order      
                    for plate_well in plate.wells.all():
                        contenders = Sample.objects.filter(wells=plate_well)
                        if contenders.count() > 0:
                            sample = contenders[0]
                            break

                # If we didn't find a sample already associated with the Factory order, create it
                if not sample:
                    sample = Sample.objects.create(vendor=factory_order.vendor.name,
                                                   part=part)

                sample.save()
                sample.wells.add(well)
                sample.save()
```
was the part that I was looking for, and it looked good to me!

**Comment by Koeng101** [comment]
> And you want to update the server then?

I put in a very simple pull request, if that is merged then updating the server would be great.

**Comment by vsoch** [comment]
Actually there is one check I want to run by you - the part you linked:

```
                # Look for a Sample for a Part WITHIN a FactoryOrder
                sample = None
                for plate in factory_order.plates.all():
```
That is looking for plates within the factory order selected by the user - do you want this to be any factory order? We'd need another loop :P

**Comment by Koeng101** [comment]
> within the factory order selected by the user 

We should only look through the factory order selected by the user, I think

**Comment by vsoch** [comment]
Ok then It’s good.

**Pull request merged**
