### PR TITLE
Adding production table to factory page, organizing into tabs

### LINKED ISSUE #91: "Production Board" for the Factory
We would like a production board for the orders currently in the database:

Basically, this will display a few pieces of information in a basic table.

`Order name, number of parts(total), status, estimated price`

And if `status` == `'Completed'`, we have a few more columns

` number of parts(completed), number of parts(failed), How long the order took (time end - time start), real price`.

For each category with `parts`, there should be a clickable link to a view those parts.

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add the production table view to the factory incoming page, along with better organizing the content into tabs. Specifically, here is the new view:

factory_incoming

With the production table being the default tab since it will most likely be wanted. The Parts link goes to the table of all associated parts. The second tab "Actions" encompasses the previous main content actions to import parts/plates from twist:

factory_incoming_actions

Currently, we don't have logic to render parts completed/finished as this data is not clearly represented anywhere, and also note that all the parts for this dummy order don't have any kind of status. We can add that when @Koeng101 describes the logic for how he would like this to work. This will close #91 

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by Koeng101** [comment]
For Parts, could we get the number of parts as a clickable link instead of just "view parts"?

**Comment by vsoch** [comment]
The Number of Parts is in the second column (Total: 45) and we do that because there will eventually be other counts (completed, failed) as sub-rows in that column. Are you saying you want this information duplicated, e.g., "View 45 Parts" ?

**Comment by vsoch** [comment]
The status is a manually set field - it's more likely that a lab staff will forget to update it. On the other hand, as soon as there is a "finish_date" we can be sure that it's finished :) No additional work is required by the staff, and the variable won't rely on this manual change.

**Comment by Koeng101** [comment]
> No additional work is required by the staff, and the variable won't rely on this manual change

True!

**Comment by vsoch** [comment]
okay we're live! Could you test the Plate import again? It's rendering the correct interface now, and the FactoryOrder table (production table) is also live.

**Pull request merged**
